"""remove_post_model

Revision ID: 6620af7d2b5b
Revises: eccb9d5a7276
Create Date: 2024-10-25 11:21:51.871163

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6620af7d2b5b'
down_revision: Union[str, None] = 'eccb9d5a7276'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop tables in order of dependencies
    op.drop_index('ix_rate_limit_tier_id', table_name='rate_limit')
    op.drop_index('ix_user_tier_id', table_name='user')

    # Drop foreign key constraints first
    op.drop_constraint('rate_limit_tier_id_fkey', 'rate_limit', type_='foreignkey')
    op.drop_constraint('user_tier_id_fkey', 'user', type_='foreignkey')

    # Drop the tier_id columns
    op.drop_column('rate_limit', 'tier_id')
    op.drop_column('user', 'tier_id')

    # Finally drop the tier table
    op.drop_table('tier')

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_blacklist',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='token_blacklist_pkey')
    )
    op.create_index('ix_token_blacklist_token', 'token_blacklist', ['token'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_tier_id'), table_name='user')
    op.drop_index(op.f('ix_user_is_deleted'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_rate_limit_tier_id'), table_name='rate_limit')
    op.drop_table('rate_limit')
    # ### end Alembic commands ###
