agents:
  - name: Subtitle Translator
    image_path: ./images/subtitle_translator.png
  - name: Subtitle Generator
    image_path: ./images/subtitle_generator.png
  - name: Image Parser
    image_path: ./images/image_parser.png
  - name: Text Summarizer
    image_path: ./images/text_summarizer.png
  - name: Web Scraper
    image_path: ./images/web_scraper.png
  - name: PDF Parser
    image_path: ./images/pdf_parser.png
